---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Full environment."

Parameters:
  VpcSubnetCidrs:
    Type: String
    Default: "10.0.0.0/16"
  
  Bucket:
    Type: String
    Default: "cerulean-operations"

Resources:
  # Create the VPC and subnets
  VpcSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${Bucket}.s3.amazonaws.com/deploying-containers-aws/network-vpc-subnets.yml
      Parameters:
        VpcSubnetCidrs: !Ref VpcSubnetCidrs


  # Create the internet access
  InternetAccess:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${Bucket}.s3.amazonaws.com/deploying-containers-aws/network-internet-access.yml
      Parameters:
        VpcId: !GetAtt VpcSubnets.Outputs.VpcId
        Subnets: !Sub 
          - "${SubnetElbA},${SubnetElbB},${SubnetElbC}"
          - {SubnetElbA: !GetAtt VpcSubnets.Outputs.SubnetElbA, SubnetElbB: !GetAtt VpcSubnets.Outputs.SubnetElbB, SubnetElbC: !GetAtt VpcSubnets.Outputs.SubnetElbC}
        

  # Create NAT gateway for network address translation
  NAT:
    Type: AWS::CloudFormation::Stack
    DependsOn: InternetAccess
    Properties:
      TemplateURL: !Sub https://${Bucket}.s3.amazonaws.com/deploying-containers-aws/network-nat.yml
      Parameters:
        VpcId: !GetAtt VpcSubnets.Outputs.VpcId
        PublicSubnet: !GetAtt VpcSubnets.Outputs.SubnetElbA
        PrivateSubnets:  !Sub
          - "${SubnetNodesA},${SubnetNodesB},${SubnetNodesC}"
          - {SubnetNodesA: !GetAtt VpcSubnets.Outputs.SubnetNodesA, SubnetNodesB: !GetAtt VpcSubnets.Outputs.SubnetNodesB, SubnetNodesC: !GetAtt VpcSubnets.Outputs.SubnetNodesC}

Outputs:
  ElbSubnets:
    Description: "List of subnet IDs for ELB"
    Value: !Sub 
      - "${SubnetElbA},${SubnetElbB},${SubnetElbC}"
      - {SubnetElbA: !GetAtt VpcSubnets.Outputs.SubnetElbA, SubnetElbB: !GetAtt VpcSubnets.Outputs.SubnetElbB, SubnetElbC: !GetAtt VpcSubnets.Outputs.SubnetElbC}
    Export:
      Name: !Sub ${AWS::StackName}-ElbSubnets
  
  NodeSubnets:
    Description: "List subnet IDs for NODES"
    Value: !Sub 
          - "${SubnetNodesA},${SubnetNodesB},${SubnetNodesC}"
          - {SubnetNodesA: !GetAtt VpcSubnets.Outputs.SubnetNodesA, SubnetNodesB: !GetAtt VpcSubnets.Outputs.SubnetNodesB, SubnetNodesC: !GetAtt VpcSubnets.Outputs.SubnetNodesC}
    Export:
      Name: !Sub ${AWS::StackName}-NodeSubnets
      