apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello
  labels:
    app: nginx
spec:
  replicas: 3
  selector: # allows the deployment to find the pods
    matchLabels:
      app: nginx
  # the following is for the POD
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello
          ports:
            - containerPort: 80
